### ISSUE TITLE
price calculation error ?

### ISSUE THREAD

**Issue by joncolas** [awslabs/ec2-spot-labs#1]
I think something strange is happening in this script:

$ python get_spot_duration.py --region us-east-1 --product-description 'Linux/UNIX' --bids c3.2xlarge:0.42
Duration	Instance Type	Availability Zone
11.4	c3.2xlarge	us-east-1a
1.0	c3.2xlarge	us-east-1e
0.6	c3.2xlarge	us-east-1d
0.4	c3.2xlarge	us-east-1b
0.3	c3.2xlarge	us-east-1c

I think AZ us-east-1a is under stable price of 0.42 $ during 11 hours dollar but in aws spot history graph shows that the price is stable with 4.2 $ instead of 0.42 $

![screenshot at 16-54-00](https://cloud.githubusercontent.com/assets/8049798/19973658/2214f87e-a1e6-11e6-8aab-9ce1d29706b1.png)

Greetings and thanks!

**Comment by schmutze** [comment]
get_spot_duration.py is legacy and no longer useful with the [new Spot pricing model](https://aws.amazon.com/blogs/compute/new-amazon-ec2-spot-pricing/)
