### ISSUE TITLE
echoing pid is a static number

### ISSUE THREAD

**Issue by natefox** [awslabs/ec2-spot-labs#2]
```
$ grep 'echo' /etc/init/spot-instance-termination-notice-handler.conf
echo 2791 > /var/run/spot-instance-notice-handler.pid
```

This is because the `$$` isn't escaped like the other dollar signs in other files. Other option is to quote the EOF so the dollar signs arent processed on the fly (and therefore not need to quote the dollar signs):
```
cat <<"EOF" > /etc/init/spot-instance-termination-notice-handler.conf
```

**Comment by schmutze** [comment]
Good catch- thanks @natefox !
