### ISSUE TITLE
Any lambda function to request spot fleet during specific time..?

### ISSUE THREAD

**Issue by vdoodala** [awslabs/ec2-spot-labs#6]
Is there any possibility for lambda function to request spot fleet during specific time..?

**Comment by schmutze** [comment]
You could try using [scheduled scaling with Spot Fleet](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-scheduled-scaling.html). Otherwise a [Lambda scheduled expression using cron](https://docs.aws.amazon.com/lambda/latest/dg/tutorial-scheduled-events-schedule-expressions.html).
